
version: 2

sources:
  - name: airbnb_bronze
    database: airbnb 
    schema: source_schema
    tables:
      - name: listings
        freshness: 
          error_after:
            count: 10
            period: day
          warn_after:
            count: 1
            period: hour
        
      - name: hosts
        freshness: 
          error_after:
            count: 10
            period: day
          warn_after:
            count: 1
            period: hour

      - name: reviews
        freshness: 
          error_after:
            count: 10
            period: day
          warn_after:
            count: 1
            period: hour


models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: listing_model
      description: This model is transfering data from source_schema.listings table (bronze layer) to silver.
      columns:
        - name: id
          tests:
            - unique
            - not_null
      

    - name: hosts_model
      description: This model is transfering data from source_schema.hosts table (bronze layer) to silver.
      columns:
        - name: id
          tests:
            - unique
            - not_null 


    - name: reviews_model
      description: This model is transfering data from source_schema.reviews table (bronze layer) to silver.
      columns:
        - name: id  
          tests:
            - unique
            - not_null